# Generated by Django 2.1.7 on 2019-02-20 19:05

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('watches', models.CharField(default=1, max_length=1000)),
                ('desc', models.CharField(max_length=200)),
                ('keywords', models.CharField(default=200, max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
