# Generated by Django 2.1.7 on 2019-02-24 17:51

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='Url')),
                ('preview_text', models.CharField(default='', max_length=55, verbose_name='Превью текст')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='uploads/preview/', verbose_name='Превью изображение')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='uploads/details/', verbose_name='Детальное изображение')),
                ('watches', models.CharField(default=1, max_length=1000, verbose_name='Кол-во просмотров')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Мета "Description"')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Мета "Keywords"')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
