# Generated by Django 2.1.7 on 2019-02-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business_card_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='preview_text',
            field=models.CharField(default='', max_length=55),
        ),
    ]
