# Generated by Django 2.1.7 on 2019-02-24 15:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_business_card_blog', '0002_blogarticles_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
