# Generated by Django 2.1.7 on 2019-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business_card_blog', '0003_auto_20190224_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
