# Generated by Django 2.1.7 on 2019-02-24 15:44

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business_card_blog', '0005_auto_20190224_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мета "Description"'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/details/', verbose_name='Детальное изображение'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мета "Keywords"'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/preview/', verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='preview_text',
            field=models.CharField(default='', max_length=55, verbose_name='Превью текст'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='watches',
            field=models.CharField(default=1, max_length=1000, verbose_name='Кол-во просмотров'),
        ),
    ]
