# Generated by Django 2.1.7 on 2019-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business_card_blog', '0006_auto_20190224_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='Url'),
        ),
    ]
